-- Migration 0001: core schema for MarketFlow (Cloudflare D1 / SQLite).
--
-- Conventions
--  * IDs are TEXT (UUIDs generated by the application layer).
--  * Monetary values are stored in INTEGER minor units (cents), never floats.
--    JPY is stored in whole yen (0 minor units). See shared/domain/money.
--  * Quantities are REAL to support fractional shares (0.003).
--  * Timestamps are TEXT ISO-8601 UTC, e.g. 2026-09-18T10:15:30.000Z.

CREATE TABLE IF NOT EXISTS users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL,
  display_name  TEXT NOT NULL,
  base_currency TEXT NOT NULL DEFAULT 'EUR',
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS portfolios (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  description   TEXT,
  base_currency TEXT NOT NULL DEFAULT 'EUR',
  is_default    INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- A ticker is not globally unique: identity is (symbol, exchange). ISIN is a
-- secondary, optional identifier and must be unique when present.
CREATE TABLE IF NOT EXISTS assets (
  id          TEXT PRIMARY KEY,
  symbol      TEXT NOT NULL,
  name        TEXT NOT NULL,
  asset_type  TEXT NOT NULL CHECK (
    asset_type IN ('STOCK', 'ETF', 'REIT', 'BOND', 'FUND', 'CRYPTO', 'CASH', 'OTHER')
  ),
  exchange    TEXT,
  currency    TEXT NOT NULL,
  isin        TEXT,
  sector      TEXT,
  industry    TEXT,
  country     TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Transactions are the source of truth for positions.
CREATE TABLE IF NOT EXISTS transactions (
  id               TEXT PRIMARY KEY,
  portfolio_id     TEXT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  asset_id         TEXT REFERENCES assets(id) ON DELETE SET NULL,
  transaction_type TEXT NOT NULL CHECK (
    transaction_type IN (
      'BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL', 'FEE',
      'INTEREST', 'TAX', 'SPLIT', 'TRANSFER_IN', 'TRANSFER_OUT', 'OTHER'
    )
  ),
  quantity       REAL NOT NULL DEFAULT 0,
  price_minor    INTEGER NOT NULL DEFAULT 0,
  fees_minor     INTEGER NOT NULL DEFAULT 0,
  taxes_minor    INTEGER NOT NULL DEFAULT 0,
  currency       TEXT NOT NULL,
  exchange_rate  REAL NOT NULL DEFAULT 1,
  transaction_date TEXT NOT NULL,
  notes          TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Derived projection of transactions. MUST always be rebuildable from
-- `transactions`; never treat it as the source of truth.
CREATE TABLE IF NOT EXISTS portfolio_holdings (
  id                 TEXT PRIMARY KEY,
  portfolio_id       TEXT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  asset_id           TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  quantity           REAL NOT NULL DEFAULT 0,
  average_cost_minor INTEGER NOT NULL DEFAULT 0,
  total_cost_minor   INTEGER NOT NULL DEFAULT 0,
  currency           TEXT NOT NULL,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (portfolio_id, asset_id)
);

CREATE TABLE IF NOT EXISTS dividend_payments (
  id                       TEXT PRIMARY KEY,
  portfolio_id             TEXT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  asset_id                 TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  amount_gross_minor       INTEGER NOT NULL DEFAULT 0,
  tax_amount_minor         INTEGER NOT NULL DEFAULT 0,
  amount_net_minor         INTEGER NOT NULL DEFAULT 0,
  currency                 TEXT NOT NULL,
  ex_date                  TEXT NOT NULL,
  record_date              TEXT,
  payment_date             TEXT,
  shares                   REAL NOT NULL DEFAULT 0,
  dividend_per_share_minor INTEGER NOT NULL DEFAULT 0,
  status                   TEXT NOT NULL CHECK (
    status IN ('EXPECTED', 'CONFIRMED', 'RECEIVED', 'CANCELLED')
  ),
  created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS watchlists (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS watchlist_items (
  id                 TEXT PRIMARY KEY,
  watchlist_id       TEXT NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
  asset_id           TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  target_price_minor INTEGER,
  target_currency    TEXT,
  notes              TEXT,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (watchlist_id, asset_id)
);

-- Daily + intraday price history. `price_date` (YYYY-MM-DD) enables fast daily
-- lookups; `timestamp` keeps full precision for future intraday data.
CREATE TABLE IF NOT EXISTS asset_prices (
  id          TEXT PRIMARY KEY,
  asset_id    TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  price_minor INTEGER NOT NULL,
  currency    TEXT NOT NULL,
  price_date  TEXT NOT NULL,
  timestamp   TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'seed',
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS fx_rates (
  id             TEXT PRIMARY KEY,
  base_currency  TEXT NOT NULL,
  quote_currency TEXT NOT NULL,
  rate           REAL NOT NULL,
  rate_date      TEXT NOT NULL,
  timestamp      TEXT NOT NULL,
  source         TEXT NOT NULL DEFAULT 'seed',
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Precomputed daily portfolio value so historical charts do not require
-- replaying every transaction on each request.
CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id                    TEXT PRIMARY KEY,
  portfolio_id          TEXT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
  snapshot_date         TEXT NOT NULL,
  market_value_minor    INTEGER NOT NULL DEFAULT 0,
  invested_capital_minor INTEGER NOT NULL DEFAULT 0,
  cash_value_minor      INTEGER NOT NULL DEFAULT 0,
  income_minor          INTEGER NOT NULL DEFAULT 0,
  base_currency         TEXT NOT NULL,
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (portfolio_id, snapshot_date)
);
